version = 1
SPDX-PackageName = "Todosaurus"
SPDX-PackageSupplier = "Friedrich von Never <friedrich@fornever.me>"
SPDX-PackageDownloadLocation = "https://github.com/ForNeVeR/Todosaurus"

[[annotations]]
path = [
    "**/.idea/**/**",
    "cli/*.DotSettings"
]
precedence = "override"
SPDX-FileCopyrightText = "2024-2026 Todosaurus contributors <https://github.com/ForNeVeR/Todosaurus>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "intellij/.run/*.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2000-2021 JetBrains s.r.o."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "intellij/gradle/wrapper/gradle-wrapper.jar",
    "intellij/gradle/wrapper/gradle-wrapper.properties"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Gradle authors <https://gradle.org/>"
SPDX-License-Identifier = "Apache-2.0"
