# SPDX-FileCopyrightText: 2000-2021 JetBrains s.r.o.
# SPDX-FileCopyrightText: 2024-2025 Todosaurus contributors <https://github.com/ForNeVeR/Todosaurus>
#
# SPDX-License-Identifier: MIT AND Apache-2.0

[versions]
gradleIntelliJPlatform = "2.11.0"
ideaSdk = "2025.3"
junit5 = "6.0.3"
kotlin = "2.2.20"

[libraries]
intelliJPlatformModulePlugin = { group = "org.jetbrains.intellij.platform.module", name = "org.jetbrains.intellij.platform.module.gradle.plugin", version.ref = "gradleIntelliJPlatform" }
intelliJPlatformPlugin = { group = "org.jetbrains.intellij.platform", name = "org.jetbrains.intellij.platform.gradle.plugin", version.ref = "gradleIntelliJPlatform" }
junit4 = "junit:junit:4.13.2"
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit5" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
changelog = "org.jetbrains.changelog:2.5.0"
gradleJvmWrapper = "me.filippov.gradle.jvm.wrapper:0.15.0"
qodana = "org.jetbrains.qodana:2025.3.1"
